### GENERAL CONFIG ###

# unique identifier for metrics calculation experiment
exp_id: "review-pixels-20241018"
logging_level: DEBUG
# debugging flag, so that we don't try and go trough all the samples
# set to False or integer (num of samples to pick)
debugging: false
# If set to false, existing contingency tables will simply be used to compute metric values
accumulate: true
# number of chunks to divide the timestamps in for parallelization
# for NO parallelization set to 0
# otherwise set to a positive integer smalller than the number of test samples
# recommended is to set equal or bigger to the number of available processing units
n_chunks: 320
n_workers: 10

### PATH RELATED CONFIG ###
path:
  root: "/data/jenna/cell-tracking-article/results/{id}"
  # template path to the files recording the final values of metrics that have been calculated
  metrics: "/data/jenna/cell-tracking-article/results/{id}/{metric}_{method}.nc"
  # template path for the dump file storing metric states
  states: "/data/jenna/cell-tracking-article/results/{id}/metric_states/state_{method}_{metric}.dump"
  # the path to the text file containing a list of timestamps to calculate metrics on
  # timestamps: "/fmi/scratch/project_2005001/3d-ml-nowcasting/datelists/swiss_rainy_days_150_52021_92023_predict-11.txt"
  timestamps: "/home/users/ritvanen/koodaus/cell-tracking-article-code/datelists/swiss_rainy_days_150_52021_92023_test.txt"
  # the path to the CSV file recording which metrics have been calculated
  done: "/data/jenna/cell-tracking-article/results/{id}/done_{id}.csv"
  # where to save copy of the input config
  config_copy: "/data/jenna/cell-tracking-article/results/{id}/{id}_config.yaml"
  # the path to the file containing logging output for the experiment
  logging: "/data/jenna/cell-tracking-article/results/{id}/{id}.log"

### PREDICTION RELATED CONFIG ###

# which prediction method name to calculate the metrics on
# and path to the predictions
methods:
  # L-CNN trained with Swiss data
  lcnn-diff-rmse-31012024:
    path: /data/jenna/cell-tracking-article/nowcasts/lcnn/lcnn_diff_rmse_swiss_31012024.h5
  # Extrapolation nowcast
  extrapolation:
    path: /data/jenna/cell-tracking-article/nowcasts/pysteps/extrapolation_swiss_composite_bbox_26012024.h5
  # LINDA nowcast
  linda:
    path: /data/jenna/cell-tracking-article/nowcasts/pysteps/linda_domain_swiss_composite_bbox_26012024.h5
  # S-PROG nowcast
  sprog:
    path: /data/jenna/cell-tracking-article/nowcasts/pysteps/sprog_swiss_composite_bbox_26012024.h5

# measurement path
measurements:
  name: measurements
  path: /data/jenna/cell-tracking-article/nowcasts/observations/swiss_composite_bbox_26012024.h5

# data related pre-processing configuration
preprocessing:
  #convert dBZ to mm/h ?
  convert_mmh: false
  #threshold for observable precipitation (after possible conversion)
  threshold: 0.15
  #value to apply to pixels below observable precipitation
  zerovalue: 0.0

  # R(Z) parameters
  zr_a: 316.0
  zr_b: 1.5

# leadtimes to calculate the metrics for as units of 5 minutes
n_leadtimes: 12
prev_obs_times: 0
# if set to True, will mask all predictions the same, using "logical and" operation
common_mask: True

### METRICS RELATED CONFIG ###

# Possible choices are defined in pincast_verif.metric_tools.get_metric_class
# an entry for each metric to be calculated
metrics:
  CONT:
    init_kwargs:
      cont_metrics: ["MAE", "ME", "RMSE", "MSE"]
      thresh: [0.1, 0.5, 1.0, 4.6, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 50.0]
      leadtimes: [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          # 13,
          # 14,
          # 15,
          # 16,
          # 17,
          # 18,
          # 19,
          # 20,
          # 21,
          # 22,
          # 23,
          # 24,
        ]
  CAT:
    init_kwargs:
      cat_metrics: ["POD", "FAR", "CSI", "ETS"]
      leadtimes: [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          # 13,
          # 14,
          # 15,
          # 16,
          # 17,
          # 18,
          # 19,
          # 20,
          # 21,
          # 22,
          # 23,
          # 24,
        ]
      thresh: [0.1, 0.5, 1.0, 4.6, 5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 50.0]
